schema_version = "1.0.0"

id = "wiggle_2"
version = "2.1.0"
name = "Wiggle 2 (5.0 Patched)"
tagline = "Wiggle bones with 5.0 compatibility and multi-select support."
maintainer = "mayaIhc"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
[authors]
name = "shteeve3d, Chamiseul"
tags = ["Animation", "Rigging", "Physics"]

[links]
homepage = "https://github.com/mayalhc/blender-wiggle-2" 
repository = "https://github.com/mayalhc/blender-wiggle-2"
"Original Project" = "https://github.com/shteeve3d/blender-wiggle-2"

[permissions]


